# Generated by Django 5.0.7 on 2024-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0002_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='passed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
